Mod04/Fazsoft.Store/Fazsoft.Store.UI/Controllers/CategoriasController.cs
using Fazsoft.Store.Domain.Contracts.Data;
using Fazsoft.Store.Domain.Contracts.Repositories;
using Fazsoft.Store.Domain.Entities;
using Fazsoft.Store.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fazsoft.Store.UI.Controllers
{
    [Authorize]
    public class CategoriasController : Controller
    {
        private readonly ICategoriaRepository _categoriaRepository;
        private readonly IUnitOfWork _uow;

        public CategoriasController(
            ICategoriaRepository categoriaRepository
            , IUnitOfWork uow)
        {
            _categoriaRepository = categoriaRepository;
            _uow = uow;
        }

        public async Task<IActionResult> Index()
        {
            var model = (await _categoriaRepository.GetAllWithProdutos())
                            .Select(x => x.ToCategoriaIndexVM());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int id)
        {
            // ViewBag.Categorias = categorias;
            var model = new CategoriaAddEditVM { };

            if (id > 0)
            {
                var data = await _categoriaRepository.GetAsync(id);
                model = data.ToCategoriaAddEditVM();
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddEdit(int id, CategoriaAddEditVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var categoria = model.ToData();

            if (id == 0)
            {
                _categoriaRepository.Add(categoria);
            }
            else
            {
                categoria.Id = id;
                categoria.DataAlteracao = DateTime.Now;
                _categoriaRepository.Update(categoria);
            }

            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }


        [HttpDelete]
        public async Task<IActionResult> Excluir(int id)
        {
            var categoria = await _categoriaRepository.GetAsync(id);

            if (categoria == null)
            {
                return BadRequest($"Item {id} não encontrado!");
            }
            var countprod = await CountProdAsync(categoria.Id);
            if ( countprod > 0)
            {
                return BadRequest($"Essa categoria possui {countprod} produtos!");
            }
            _categoriaRepository.Delete(categoria);

            await _uow.CommitAsync();

            return NoContent();

        }

        private async Task<int> CountProdAsync(int categoriaId)
        {
            return await _categoriaRepository.CountProdAsync(categoriaId);
        }
    }
}

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Views/Categorias/AddEdit.cshtml
@model CategoriaAddEditVM
@{
    int id = Convert.ToInt32(ViewContext.RouteData.Values["id"]);

    ViewBag.Title = ( id == 0 ? "Adicionar" : "Editar");
    ViewBag.SubTitle = (id == 0 ? "Adicionar Nova Categoria" : $"Editar Categoria {id}");
}

<form method="post">
    <div class="mb-3">
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control" autofocus/>
        <span asp-validation-for="Nome" class="invalid"></span>
    </div>

    <div>
        <a class="btn btn-outline-warning" asp-action="Index" asp-controller="Categorias" >Voltar</a>
        <button class="btn btn-outline-secondary" type="submit">Salvar</button>
    </div>
</form>

@section scripts {
    <partial name="_ScriptsValidate">
}

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Views/Categorias/Index.cshtml
@model IEnumerable<CategoriaIndexVM>
@{
    ViewBag.Title = "Listagem de Categorias";
    ViewBag.SubTitle = "Listagem de Categorias Cadastados no Sistema!!";

}


<div>
    <a asp-controller="Categorias" asp-action="AddEdit" class="btn btn-outline-secondary">Adicionar Categoria</a>
</div>

<div>
    <table class="table  table-striped table-hover">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Data de Cadastro</th>
                <th>Quantidade Produtos</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="item-@item.Id">
                    <td>@item.Nome</td>
                    <td>@item.DataCadastro.ToShortDateString()</td>
                    <td>@item.QtddProdutos</td>
                    <td>
                        <a class="btn btn-outline-success btn-sm" asp-action="AddEdit" asp-controller="Categorias" asp-route-id="@item.Id">Editar</a>
                        <button type="button" class="btn btn-outline-danger btn-sm" onclick="excluir(@item.Id, '@item.Nome', 'Categoria', '@Url.Action("Excluir","Categorias")')">Excluir</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<partial name="_modalDel">


    @section scripts{
        <script src="~/js/dell-modal.js"></script>
    }