Mod04/Fazsoft.Store/Fazsoft.Store.UI/Controllers/AuthController.cs
using Fazsoft.Store.Domain.Contracts.Repositories;
using Fazsoft.Store.UI.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Fazsoft.Store.UI.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        public AuthController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        [HttpGet]
        public IActionResult Login() => View();


        [HttpPost]
        public async Task<IActionResult> Login(string returnURL, AuthVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _usuarioRepository.SignInAsync(model.Email, model.Senha);

            if (user == null)
            {
                ModelState.AddModelError("", "Email ou Senha inválidos!");
                return View(model);
            }

            var claims = new List<Claim>
            {
                new Claim("nomeUsuario", user.Nome),
                new Claim("email", user.Email),
                new Claim("idUsuario", user.Id.ToString())
            };

            var identity = new ClaimsIdentity(claims
                                    , CookieAuthenticationDefaults.AuthenticationScheme
                                    , "nomeUsuario"
                                    , string.Join(", ", user.Perfis?.Select(x => x.Nome)));

            await HttpContext.SignInAsync(new ClaimsPrincipal(identity)
                                          , new AuthenticationProperties
                                          {
                                              ExpiresUtc = DateTime.UtcNow.AddMinutes(30)
                                          });

            if (string.IsNullOrEmpty(returnURL) && Url.IsLocalUrl(returnURL))
            {
                return Redirect(returnURL);
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> LogOff()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Controllers/PerfisController.cs
using Fazsoft.Store.Domain.Contracts.Data;
using Fazsoft.Store.Domain.Contracts.Repositories;
using Fazsoft.Store.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fazsoft.Store.UI.Controllers
{
    [Authorize]
    public class PerfisController : Controller
    {
        private readonly IPerfilRepository _perfilRepository;
        private readonly IUnitOfWork _uow;

        public PerfisController(
            IPerfilRepository perfilRepository
            , IUnitOfWork uow)
        {
            _perfilRepository = perfilRepository;
            _uow = uow;
        }

        public async Task<IActionResult> Index()
        {
            var model = (await _perfilRepository.GetAllWithUsuarioAsync())
                            .Select(x => x.ToPerfilIndexVM());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int id)
        {
            var model = new PerfilAddEditVM { };

            if (id > 0)
            {
                var data = await _perfilRepository.GetAsync(id);
                model = data.ToPerfilAddEditVM();
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> AddEdit(int id, PerfilAddEditVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var perfil = model.ToData();

            if (id == 0)
            {
                _perfilRepository.Add(perfil);
            }
            else
            {
                perfil.Id = id;
                perfil.DataAlteracao = DateTime.Now;
                _perfilRepository.Update(perfil);
            }

            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }


        [HttpDelete]
        public async Task<IActionResult> Excluir(int id)
        {
            var perfil = await _perfilRepository.GetAsync(id);

            if (perfil == null)
            {
                return BadRequest();
            }
            _perfilRepository.Delete(perfil);

            await _uow.CommitAsync();

            return NoContent();

        }
    }
}

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Controllers/ProdutosController.cs
using Fazsoft.Store.Data.EF;
using Fazsoft.Store.Domain.Contracts.Data;
using Fazsoft.Store.Domain.Contracts.Repositories;
using Fazsoft.Store.Domain.Entities;
using Fazsoft.Store.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Fazsoft.Store.UI.Controllers
{
    [Authorize]
    public class ProdutosController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly ICategoriaRepository _categoriaRepository;
        private readonly IUnitOfWork _uow;

        public ProdutosController(
            IProdutoRepository produtoRepository
            , ICategoriaRepository categoriaRepository
            , IUnitOfWork uow)
        {
            _produtoRepository = produtoRepository;
            _categoriaRepository = categoriaRepository;
            _uow = uow;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {            
            var produtos = (await _produtoRepository.GetAllWithCategoriaAsync())
                            .Select(x => x.ToProdutoIndexVM());

            return View(produtos);
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int id)
        {
            // ViewBag.Categorias = categorias;
            var model = new ProdutoAddEditVM { };

            if (id > 0)
            {
                var data = await _produtoRepository.GetAsync(id);
                model = data.ToProdutoAddEditVM();
            }

            await addCategoriasToModelAsync(model);

            return View(model);
        }

        private async Task addCategoriasToModelAsync(ProdutoAddEditVM model)
        {
            var categorias = await _categoriaRepository.GetAsync();
            model.Categorias = categorias.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Nome });
        }


        [HttpPost]
        public async Task<IActionResult> AddEdit(int id, ProdutoAddEditVM model)
        {
            if (!ModelState.IsValid)
            {
                await addCategoriasToModelAsync(model);
                return View(model);
            }

            var produto = model.ToData();

            if (id == 0)
            {
                _produtoRepository.Add(produto);
            }
            else
            {
                produto.Id = id;
                produto.DataAlteracao = DateTime.Now;
                _produtoRepository.Update(produto);
            }

            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }


        [HttpDelete]
        public async Task<IActionResult> Excluir(int id)
        {
            var prod = await _produtoRepository.GetAsync(id);

            if (prod == null)
            {
                return BadRequest();
            }
            _produtoRepository.Delete(prod);

           await  _uow.CommitAsync();

            return NoContent();

        }
    }
}

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Controllers/UsuariosController.cs
using Fazsoft.Store.Domain.Contracts.Data;
using Fazsoft.Store.Domain.Contracts.Repositories;
using Fazsoft.Store.Domain.Entities;
using Fazsoft.Store.Domain.Helpers;
using Fazsoft.Store.UI.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Fazsoft.Store.UI.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;
        private readonly IPerfilRepository _perfilRepository;
        private readonly IUnitOfWork _uow;

        public UsuariosController(
            IUsuarioRepository usuarioRepository
            , IPerfilRepository perfilRepository
            , IUnitOfWork uow)
        {
            _usuarioRepository = usuarioRepository;
            _perfilRepository = perfilRepository;
            _uow = uow;
        }

        public async Task<IActionResult> Index()
        {
            var model = (await _usuarioRepository.GetAllWithPerfisAsync())
                                .Select(x => x.ToUsuarioIndexVM());

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddEdit(int id)
        {
            var model = new UsuarioAddEditVM { };

            if (id > 0)
            {
                var data = await _usuarioRepository.GetByIDWithPerfisAsync(id);
                model = data.ToUsuarioAddEditVM();
                model.PerfisId = data.Perfis?.Select(x => x.Id).ToList();
            }
            await GetPerfisAsync(model);

            return View(model);
        }

        private async Task GetPerfisAsync(UsuarioAddEditVM model)
        {
            model.Perfis = (await _perfilRepository.GetAsync())
                            .Select(x => new SelectListItem { Text = x.Nome, Value = x.Id.ToString() });
        }

        [HttpPost]
        public async Task<IActionResult> AddEdit(int id, UsuarioAddEditVM model)
        {
            if (!ModelState.IsValid)
            {
                await GetPerfisAsync(model);
                return View(model);
            }

            if (id == 0)
            {
                var usuario = model.ToData();
                usuario.Senha.Encrypt();
                usuario.Perfis = await MontarPerfisAsync(model.PerfisId);
                _usuarioRepository.Add(usuario);
            }
            else
            {
                var usuario = await _usuarioRepository.GetByIDWithPerfisAsync(id);
                usuario.Id = id;
                usuario.Nome = model.Nome;
                usuario.DataAlteracao = DateTime.Now;
                usuario.Perfis = await MontarPerfisAsync(model.PerfisId);
                _usuarioRepository.Update(usuario);
            }

            await _uow.CommitAsync();

            return RedirectToAction("Index");
        }

        private async Task<IEnumerable<Perfil>> MontarPerfisAsync(IEnumerable<int> perfisId)
        {
            if (perfisId == null)
            {
                return null;
            }
            return await _perfilRepository.GetByIdsAsync(perfisId);
        }

        [HttpDelete]
        public async Task<IActionResult> Excluir(int id)
        {
            var prod = await _usuarioRepository.GetAsync(id);

            if (prod == null)
            {
                return BadRequest();
            }
            _usuarioRepository.Delete(prod);

            await _uow.CommitAsync();

            return NoContent();

        }
    }
}

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="h-100">
<head>
    <meta name="viewport" content="width=device-width">
    <meta charset="utf-8">
    <!-- CSS only -->
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">*@
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/estilo.css" rel="stylesheet" />
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">*@
    <link href="~/node_modules/toastr/build/toastr.min.css" rel="stylesheet" />
    <title>Fazsoft Store | @ViewBag.Title</title>
</head>
<body class="d-flex flex-column h-100">
    <header>
        @await Html.PartialAsync("_menuTop");
    </header>

    <!-- Begin page content -->
    <main class="flex-shrink-0">
        <div class="container">
            <h1 class="mt-5">@ViewBag.Title</h1>
            <p class="lead">@ViewBag.SubTitle</p>
            @RenderBody()
        </div>
    </main>

    <footer class="footer mt-auto py-3 bg-light">
        <div class="container">
            <span class="text-muted">Desenvolvido por FazSoft</span>
        </div>
    </footer>

    <!-- JavaScript Bundle with Popper -->
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>*@

    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/toastr/build/toastr.min.js"></script>
    @RenderSection("scripts", false);
</body>
</html>

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Views/Shared/_ScriptsValidate.cshtml
@*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" integrity="sha512-o6XqxgrUsKmchwy9G5VRNWSSxTS4Urr4loO6/0hYdpWmFUfHqGzawGxeQGMDqYzxjY9sbktPbNlkIQJWagVZQg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>*@
<script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
<script src="~/js/jquery.validate.extensions.js"></script>
<script src="~/js/jquery.validate.pt-BR.js"></script>

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Views/Shared/_menuTop.cshtml
 <!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">FazSoft Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Página Inicial</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="About" asp-controller="Home">Sobre</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Produtos">Produtos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Categorias">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Usuarios">Usuarios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Perfis">Perfis</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">

                @if (!User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Login" asp-controller="Auth">Login</a>
                    </li>
                }
                else
                {
                    <li class="nav-item" dropdown>

                    </li>
                }


            </ul>
        </div>
    </div>
</nav>

Mod04/Fazsoft.Store/Fazsoft.Store.UI/Views/Shared/_modalDel.cshtml
<!-- Modal -->
<div class="modal fade" id="excluirModal" tabindex="-1" aria-labelledby="excluirModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="excluirModalLabel">Excluir</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Gostaria de excluir <span id="modalBody-desc" class="badge bg-danger"></span>?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-outline-danger" onclick="confirmDel()">Confirmar</button>
            </div>
        </div>
    </div>
</div>